name: Test build
on: [push]

jobs:
  build:
    name: Build dist files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Build files
        run: |
          ./build.sh
          cd dist
          zip -r nadyui.zip *
          mv nadyui.zip ..

      - name: Extract branch name
        run: |
          BRANCH="$(git rev-parse --abbrev-ref HEAD)"
          echo ::set-output name=branch::$(echo ${BRANCH})
        id: extract_branch

      - name: Upload build artifact
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ci-${{ steps.extract_branch.outputs.branch }}
          name: ${{ steps.extract_branch.outputs.branch }}
          body: |
              Automated CI build done by ${{ github.actor }} from commit ${{ github.sha }}
          prerelease: true
          files: |
            nadyui.zip
